### ISSUE TITLE
Add next and previous annotation buttons at the top of the annotation text window

### ISSUE THREAD

**Issue by jeau** [NCSU-Libraries/annona#17]
thanks for this work 

I'd like to see one more feature come in to improve usability for users: add next and previous annotation buttons on the right top of the annotation text window. Of course, this feature could be enabled or (by default) disabled.

Jeau

**Comment by dnoneill** [comment]
@jeau Just checking before I merge the change into the repository, this is what you were looking for: 
<img width="975" alt="Screen Shot 2021-04-20 at 7 38 54 PM" src="https://user-images.githubusercontent.com/19173991/115476585-26427c80-a210-11eb-9962-51d9819c8acd.png">

**Comment by jeau** [comment]
yes, great thank's
