### ISSUE TITLE
add pct support

### ISSUE THREAD

**Issue by dnoneill** [NCSU-Libraries/annona#19]

**Comment by dnoneill** [comment]
@waldenn I have looked at the annotation spec again and it does not support pct. It looks like IIIF Image server supports pct. I went ahead and added support for pct but it requires a bit of change for the annotations you have created. Instead of #pct= I worked around this with #xwyh=pct:x,y,w,h

**Comment by waldenn** [comment]
Oh, nice! I will try to use your tooling soon to render some annotation boxes. Thanks!
