### ISSUE TITLE
Support for v3 annotationPages that link to a manifest

### ISSUE THREAD

**Issue by glenrobson** [NCSU-Libraries/annona#35]
Hi @dnoneill 

Do you support v3 annotationPages as a parameter to Annona? I've been doing some testing on the following page adding the equivalent of `within` in IIIF 2 to some v3 annotations:

https://glenrobson.github.io/iiif_stuff/zooniverse/partof/

I think the annotation structure is correct and equivalent to the v2 within structure. It works in Mirador but it maybe because I suggested it [here](https://github.com/ProjectMirador/mirador-annotations/issues/20#issuecomment-663157941). 

Do you do it differently or is it not something you've come across? 

Thanks

**Comment by dnoneill** [comment]
@glenrobson Yes it does support v3, however it expects partOf to be in the "source" field. I will go ahead and fix this and have the fix pushed by end of day.

**Comment by dnoneill** [comment]
@glenrobson Should work now. You can also load the manifest into the range storyboard if you want to show all of annotation pages: <iiif-rangestoryboard rangeurl='https://glenrobson.github.io/iiif_stuff/zooniverse/partof/manifest.json'></iiif-rangestoryboard>

**Comment by glenrobson** [comment]
Thanks @dnoneill its working great now.
