### ISSUE TITLE
Add a iiif-content query parameter 

### ISSUE THREAD

**Issue by glenrobson** [NCSU-Libraries/annona#4]
During the Online IIIF Workshop last week we use the following Gitbook:

https://training.iiif.io/iiif-online-workshop/index.html

Participants were encouraged to have a IIIF image by day 2, a manifest by day 3 and a manifest with annotations by day 4. It would be great if we could add Annona as an example to day 4 to say now you've annotated your manifest using the SimpleAnnotationServer and Mirador here is a way to display those annotations in another tool. 

For the workshop most participants don't have HTML skills and don't have access to web hosting so they use the [Chrome Web Server](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en) to host their manifests and annotation lists. We used the Internet Archive for hosting IIIF images. 

With this in mind it would be great if we could pass the AnntationList as a URL query parameter to a hosted version of Annona so participants can see their annotations in a different viewer. An example URL might be:

https://ncsu-libraries.github.io/annona/storyboard/#?iiif-content=http://localhost:8887/annotations.json

Although I've just realised this might cause problems as the localhost is http.... but I could host a http version of Annona for the workshop. Other examples of this type of deep linking we use in the workshop include:

## Image API:
 * UCD Image tool: https://jbhoward-dublin.github.io/IIIF-imageManipulation/index.html?imageID=https://iiif.archivelab.org/iiif/img-8664
 * Open sea dragon: https://iiif.gdmrdigital.com/openseadragon/index.html?image=https://iiif.archivelab.org/iiif/img-8664/info.json

## Presentation API:
 * Various IIIF Viewers https://iiif.io/explainers/using_iiif_resources/#quick-links

The reason for using the `iiif-content` name is to link it to the Content state api, and I think this would be allowable as it states a IIIF resource rather than a Manifest:

https://iiif.io/api/content-state/0.2/#224-target-url

I tested Annona with one of the SAS exported annotation lists and it worked great!

**Comment by dnoneill** [comment]
@glenrobson I have added a display url to the Annona tag builder so users can build their views however they want. Here is an example. I don't foresee any problems with this. Please feel free to point out any issues you see that may arise. If you want to host this locally all the files are in the docs folder.

Here is an example: https://ncsu-libraries.github.io/annona/tools/#/tag-builder?url=https%3A%2F%2Fdnoneill.github.io%2Fannotate%2Fannotations%2Ffullbayeux-list.json&viewtype=iiif-storyboard&listtype=annotationlist&settings=%7B%22tagscolor%22%3A%5B%7B%22tagvalue%22%3A%22%22,%22color%22%3A%22%22%7D%5D,%22additionalinfo%22%3A%22%22,%22fit%22%3A%22horizontal%22%7D

**Comment by glenrobson** [comment]
Sorry I forgot to say thank you for adding this. For info we have added a module on using Annona to the IIIF training:

https://training.iiif.io/iiif-online-workshop/day-four/annotations-annona.html

**Comment by dnoneill** [comment]
No problem. Thought that might have happened. That is so awesome. Thanks for sharing.
