### ISSUE TITLE
Manage dataURI for annotationurl attribute?

### ISSUE THREAD

**Issue by sebprunierserli** [NCSU-Libraries/annona#44]
We tried to configure a `<iiif-storyboard>` component with a dataURI like `data:application/json;base64,W3sidHlwZSI6IkFubm90YXRpb24iLCJib2R5IjpbeyJ0eXBlIjoiVGV4dHVhbEJvZHkiLCJ2YWx1ZSI6ImphcmRpbiIsInB1cnBvc2UiOiJjb21tZW50aW5nIn1dLCJ0YXJnZXQiOnsic291cmNlIjoiaHR0cHM6Ly9paWlmLmVtZi5mci9paWlmLzMvcGV1dGluZ2VyLmpwMiIsInNlbGVjdG9yIjp7InR5cGUiOiJTdmdTZWxlY3RvciIsInZhbHVlIjoiPHN2Zz48ZWxsaXBzZSBjeD1cIjEzMzY5LjMwOTU3MDMxMjVcIiBjeT1cIjg1Ni42NzkyOTA3NzE0ODQ0XCIgcng9XCIyNTMuODgzNzg5MDYyNVwiIHJ5PVwiMTU5LjI4MTA5NzQxMjEwOTM4XCI+PC9lbGxpcHNlPjwvc3ZnPiJ9fSwiQGNvbnRleHQiOiJodHRwOi8vd3d3LnczLm9yZy9ucy9hbm5vLmpzb25sZCIsImlkIjoiI2E1MzliZGE3LTcwNzQtNDIzZS04MDMyLTZjMWEyNjY0N2EwMCJ9XQ==` in the `annotationurl` attribute.

But it does not work :-(

Is there a way to pass annotations as "raw json" to the `<iiif-storyboard>` component ? (because our annotations are not served over http).
If not, what do you think about managing dataURI for `annotationurl` attribute ? (we can try to contribute this feature with a PR if you are ok)

**Comment by dnoneill** [comment]
@sebprunierserli You can serve "raw" json with the application. I think the idea of of a dataURI is also interesting but I have included an example with raw json below. Is dataURI still of interest to you?

<script type="application/json" id="gr1b4nhz2mkvmfs33p9mke">
[{"type":"Annotation","body":[{"type":"TextualBody","value":"jardin","purpose":"commenting"}],"target":{"source":"https://iiif.emf.fr/iiif/3/peutinger.jp2","selector":{"type":"SvgSelector","value":"<svg><ellipse cx=\"13369.3095703125\" cy=\"856.6792907714844\" rx=\"253.8837890625\" ry=\"159.28109741210938\"></ellipse></svg>"}},"@context":"http://www.w3.org/ns/anno.jsonld","id":"#a539bda7-7074-423e-8032-6c1a26647a00"}]
</script>
<iiif-storyboard annotationurl='gr1b4nhz2mkvmfs33p9mke'></iiif-storyboard>

**Comment by dnoneill** [comment]
I added dataURIs.

**Comment by sebprunierserli** [comment]
Thanks a lot for your help. And thanks also for the fix concerning the dataURI !
Everything works fine for us now.

**Comment by dnoneill** [comment]
@sebprunierserli Glad I could help. Please let me know if you have any links you can share with me, I would love to add some examples to our in the wild page. If you don't feel comfortable with that I would love any links you would be able to send me just to be able to see how the tool is being used.

**Comment by dnoneill** [comment]
@GGoetzelmann  If you remove the everything before base64, it should work. So if you have base64,[datauri];base64,[datauri];base64,[datauri] it will render.
