### ISSUE TITLE
Buttons must have accessible text

### ISSUE THREAD

**Issue by uom-mde** [NCSU-Libraries/annona#58]
Hello all,

[Further to issue #53](https://github.com/NCSU-Libraries/annona/issues/53), I've noted two additional buttons on the Annona viewer that Google Lighthouse flags as needing accessible names:
 
1. button#nextPageButton.pageButton.toolbarButton.ltr
2. button#previousPageButton.pageButton.toolbarButton.ltr

Are you able to update these, as you did the last time?

Many thanks for all your assistance.

Best wishes,
John

**Comment by dnoneill** [comment]
@uom-mde Done!

**Comment by uom-mde** [comment]
Outstanding, thank you!
